openapi: '3.0.2'
info:
  title: Artifact standardization
  description: |
    Check a database of standards to determine the expected uses of an artifact.
  version: '1.0'
  contact:
    name: Brian Hanafee
    email: bhanafee@gmail.com
    url: https://hanafee.com
servers:
  - url: https://api.server.test/v1
components:
  schemas:
    Standardization:
      description: Standardized usage of an artifact
      type: object
      required:
        - disposition
      properties:
        disposition:
          type: string
          enum: [Not Evaluated, NonStandard, Evaluation, Restricted, Standard]
        usage:
          type: string
        sunset:
          type: string
          format: date
        versions:
          type: array
          items:
            type: object
            properties:
              lifecycle:
                type: string
                enum: [R&D, Mainstream, Deprecated, Obsolete]
              blacklisted:
                type: boolean
              eol:
                type: string
                format: date
              applies:
                $ref: 'types.yml#/components/schemas/Applies'
  responses:
    Standards:
      description: The artifact is recognized and the standardization information is in the body
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Standardization'
        application/xml:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Standardization'
            xml:
              wrapped: true
              name: standards
paths:
  /standard/{packaging}/{artifact}/:
    parameters:
      - $ref: 'types.yml#/components/parameters/packagingParam'
      - $ref: 'types.yml#/components/parameters/artifactParam'
    get:
      description: Whether an artifact is standard
      operationId: getStandardsForArtifact
      tags: [artifact, standard]
      responses:
        '200':
          $ref: '#/components/responses/Standards'
        '404':
          $ref: 'types.yml#/components/responses/ArtifactNotFound'
        default:
          $ref: 'types.yml#/components/responses/Unexpected'
  /standard/{packaging}/{artifact}/{version}:
    parameters:
      - $ref: 'types.yml#/components/parameters/packagingParam'
      - $ref: 'types.yml#/components/parameters/artifactParam'
      - $ref: 'types.yml#/components/parameters/versionParam'
    get:
      description: Whether an artifact version is standard
      operationId: getStandardsForArtifactVersion
      tags: [artifact, standard]
      responses:
        '200':
          $ref: '#/components/responses/Standards'
        '404':
          $ref: 'types.yml#/components/responses/ArtifactNotFound'
        default:
          $ref: 'types.yml#/components/responses/Unexpected'
